#!/bin/sh
set -e

case "$1" in
    configure|abort-upgrade|abort-remove|abort-deconfigure)
        chown 0:0 /Applications/Veil.app/Veil
        chmod +s /Applications/Veil.app/Veil
        uicache -p /Applications/Veil.app
        ;;
esac
